FROM almalinux:9

LABEL project=awsdevops \
      env=dev \
      maintainer=akhila

ARG APP_VERSION=1.0

# Install nginx
RUN dnf install -y nginx && dnf clean all

# Configure nginx (port + pid path)
RUN sed -i 's/listen       80;/listen 8080;/' /etc/nginx/nginx.conf \
 && sed -i 's|pid /run/nginx.pid;|pid /tmp/nginx.pid;|' /etc/nginx/nginx.conf

# Create non-root user
RUN useradd -m devops

# Fix permissions (only required dirs)
RUN chown -R devops:devops \
    /usr/share/nginx \
    /var/log/nginx \
    /var/lib/nginx \
    /var/cache/nginx \
    /tmp

# Set working directory
WORKDIR /usr/share/nginx/html

# Copy app files
COPY index.html .

# Switch to non-root user
USER devops

# Set environment variable
ENV APP_VERSION=${APP_VERSION}

# Expose port
EXPOSE 8080

# Start nginx in foreground
CMD ["nginx", "-g", "daemon off;"]