FROM almalinux:9

LABEL project=awsdevops \
      env=dev \
      maintainer=akhila

ARG APP_VERSION=1.0

# Install nginx and cleanup
RUN dnf install nginx -y && dnf clean all

# Change nginx port to 8080
RUN sed -i 's/listen       80;/listen 8080;/' /etc/nginx/nginx.conf

# Create non-root user
RUN useradd -m devops

# Give permissions to devops user
RUN mkdir -p /run/nginx \
 && chown -R devops:devops \
    /run/nginx \
    /usr/share/nginx \
    /var/log/nginx \
    /var/lib/nginx \
    /var/cache/nginx

# Fix nginx PID path
RUN sed -i 's|/run/nginx.pid|/run/nginx/nginx.pid|' /etc/nginx/nginx.conf

# Set working directory
WORKDIR /usr/share/nginx/html

# Copy app files
COPY index.html .

# Switch to non-root user
USER devops

# Set environment variable
ENV APP_VERSION=${APP_VERSION}

# Document port
EXPOSE 8080

# Start nginx
CMD ["nginx", "-g", "daemon off;"]


